package com.inditex.mecc.mectlglnk.infrastructure.repository.db2;

public class JdbcQueryConstants {

  public static final String STORE_ID = "STORE_ID";

  public static final String XCATGROUP_GRID_STATEMENT =
      "SELECT DISTINCT CATGROUP_ID, GRID_ID, STORE_ID "
          + "FROM uezara.XCATGROUP_GRID "
          + "WHERE STORE_ID IN ({" + STORE_ID + "}) "
          + "AND STATUS = 'LIVE' "
          + "AND CATGROUP_ID IN "
          + "   (SELECT A.CATGROUP_ID_CHILD FROM UEZARA.CATGRPREL A INNER JOIN UEZARA.CATGROUP P ON (P.CATGROUP_ID = A.CATGROUP_ID_CHILD) "
          + "     WHERE A.CATALOG_ID IN (SELECT CATALOG_ID FROM UEZARA.XTIENDA_CATALOGO WHERE STORE_ID IN ({" + STORE_ID + "})) AND P.MARKFORDELETE = 0) "
          + "AND CATGROUP_ID NOT IN (SELECT CATGROUP_ID FROM UEZARA.XCATGROUP_ATRIB WHERE ID_XATRIBUTO_CATEGORIA IN ('HIDDEN','HIDDEN-PRO','ACCESSIBLE')) "
          + "AND CATGROUP_ID NOT IN (SELECT CATGROUP_ID FROM UEZARA.XCATGPR_EXCLUSION WHERE STORE_ID IN ({" + STORE_ID + "}))";
}
